run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - godot
    - gosec
    - exportloopref
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  godot:
    scope: declarations
    capital: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - goconst
    - path: testing/
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
